### ISSUE TITLE
App Upload error

### ISSUE THREAD

**Issue by tanatoa** [sjkp/sjkp.livechatmsteams#1]
Error while reading manifest.json
Error while reading manifest.json: Invalid value(s) specified for isNotificationOnly: "false" For more information, please visit aka.ms/teamsdocs

**Comment by thanhtien19** [comment]
I am the same error , please help

**Comment by buylife** [comment]
Upload is fine after some trick

**Comment by tanatoa** [comment]
What trick @buylife?

**Comment by buylife** [comment]
@tanatoa simply remove quotes from manifest file
line 29 and 30 
like this    
 "needsChannelSelector": true,
      "isNotificationOnly": false,

**Comment by buylife** [comment]
<img width="833" alt="screenshot 2018-11-11 14 25 20" src="https://user-images.githubusercontent.com/1515897/48312299-a1be8f00-e5bd-11e8-8c6a-21c0b84b7ef7.png">

but app wont work whatever

**Comment by sjkp** [comment]
I'm no longer supporting this devpost version of the app. Instead please use this one: 
https://appsource.microsoft.com/en-us/product/office/WA104381862?src=webduppage&tab=Overview
