### ISSUE TITLE
Upload is fine but wont work

### ISSUE THREAD

**Issue by buylife** [sjkp/sjkp.livechatmsteams#2]
Great app but wont work, not respond to any commands such as @Live Chat GetWebChats etc.. nothing happend

<img width="1045" alt="screenshot 2018-11-11 14 08 51" src="https://user-images.githubusercontent.com/1515897/48312143-5c00c700-e5bb-11e8-8c9b-ab27c570636c.png">

**Comment by buylife** [comment]
@sjkp please help

**Comment by sjkp** [comment]
@buylife hi - I'm no longer supporting the version i created for the devpost hackathon, please use the version we created at my company: https://appsource.microsoft.com/en-us/product/office/WA104381862?src=webduppage&tab=Overview
